/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as FormularioTokenRouteImport } from './routes/formulario.$token'
import { Route as AppProntuariosRouteImport } from './routes/_app.prontuarios'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppPacientesIndexRouteImport } from './routes/_app.pacientes.index'
import { Route as AppFormulariosIndexRouteImport } from './routes/_app/formularios/index'
import { Route as AppPacientesIdRouteImport } from './routes/_app.pacientes.$id'
import { Route as AppFormulariosIdEditRouteImport } from './routes/_app.formularios.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const FormularioTokenRoute = FormularioTokenRouteImport.update({
  id: '/formulario/$token',
  path: '/formulario/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProntuariosRoute = AppProntuariosRouteImport.update({
  id: '/prontuarios',
  path: '/prontuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesIndexRoute = AppPacientesIndexRouteImport.update({
  id: '/pacientes/',
  path: '/pacientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppFormulariosIndexRoute = AppFormulariosIndexRouteImport.update({
  id: '/formularios/',
  path: '/formularios/',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesIdRoute = AppPacientesIdRouteImport.update({
  id: '/pacientes/$id',
  path: '/pacientes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppFormulariosIdEditRoute = AppFormulariosIdEditRouteImport.update({
  id: '/formularios/$id/edit',
  path: '/formularios/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/prontuarios': typeof AppProntuariosRoute
  '/formulario/$token': typeof FormularioTokenRoute
  '/pacientes/$id': typeof AppPacientesIdRoute
  '/formularios/': typeof AppFormulariosIndexRoute
  '/pacientes/': typeof AppPacientesIndexRoute
  '/formularios/$id/edit': typeof AppFormulariosIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/prontuarios': typeof AppProntuariosRoute
  '/formulario/$token': typeof FormularioTokenRoute
  '/': typeof AppIndexRoute
  '/pacientes/$id': typeof AppPacientesIdRoute
  '/formularios': typeof AppFormulariosIndexRoute
  '/pacientes': typeof AppPacientesIndexRoute
  '/formularios/$id/edit': typeof AppFormulariosIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/prontuarios': typeof AppProntuariosRoute
  '/formulario/$token': typeof FormularioTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/pacientes/$id': typeof AppPacientesIdRoute
  '/_app/formularios/': typeof AppFormulariosIndexRoute
  '/_app/pacientes/': typeof AppPacientesIndexRoute
  '/_app/formularios/$id/edit': typeof AppFormulariosIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/dashboard'
    | '/prontuarios'
    | '/formulario/$token'
    | '/pacientes/$id'
    | '/formularios/'
    | '/pacientes/'
    | '/formularios/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/configuracoes'
    | '/dashboard'
    | '/prontuarios'
    | '/formulario/$token'
    | '/'
    | '/pacientes/$id'
    | '/formularios'
    | '/pacientes'
    | '/formularios/$id/edit'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/configuracoes'
    | '/_app/dashboard'
    | '/_app/prontuarios'
    | '/formulario/$token'
    | '/_app/'
    | '/_app/pacientes/$id'
    | '/_app/formularios/'
    | '/_app/pacientes/'
    | '/_app/formularios/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  FormularioTokenRoute: typeof FormularioTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/formulario/$token': {
      id: '/formulario/$token'
      path: '/formulario/$token'
      fullPath: '/formulario/$token'
      preLoaderRoute: typeof FormularioTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/prontuarios': {
      id: '/_app/prontuarios'
      path: '/prontuarios'
      fullPath: '/prontuarios'
      preLoaderRoute: typeof AppProntuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/': {
      id: '/_app/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof AppPacientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/formularios/': {
      id: '/_app/formularios/'
      path: '/formularios'
      fullPath: '/formularios/'
      preLoaderRoute: typeof AppFormulariosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/$id': {
      id: '/_app/pacientes/$id'
      path: '/pacientes/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof AppPacientesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/formularios/$id/edit': {
      id: '/_app/formularios/$id/edit'
      path: '/formularios/$id/edit'
      fullPath: '/formularios/$id/edit'
      preLoaderRoute: typeof AppFormulariosIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProntuariosRoute: typeof AppProntuariosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPacientesIdRoute: typeof AppPacientesIdRoute
  AppFormulariosIndexRoute: typeof AppFormulariosIndexRoute
  AppPacientesIndexRoute: typeof AppPacientesIndexRoute
  AppFormulariosIdEditRoute: typeof AppFormulariosIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProntuariosRoute: AppProntuariosRoute,
  AppIndexRoute: AppIndexRoute,
  AppPacientesIdRoute: AppPacientesIdRoute,
  AppFormulariosIndexRoute: AppFormulariosIndexRoute,
  AppPacientesIndexRoute: AppPacientesIndexRoute,
  AppFormulariosIdEditRoute: AppFormulariosIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  FormularioTokenRoute: FormularioTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
